name: sharemagazines
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  http: ^1.1.0
#  http: ^0.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
#  json_annotation: ^4.4.0
#  shared_preferences: ^2.0.14
  google_maps_cluster_manager: ^3.1.0
  carousel_slider: ^4.2.1
#  image: ^4.0.16
  dio: ^5.3.3
  webview_flutter: ^4.7.0
  shaky_animated_listview: ^0.0.5
  package_info_plus: ^5.0.1
  bloc_concurrency: ^0.2.0
  easy_localization: ^3.0.1
#  pdfx: ^2.3.0


#  firebase_auth: ^4.6.1
#  firebase_auth: ^3.4.2
#  firebase_core: ^1.19.2
  google_sign_in: ^6.2.1
  loading_animation_widget: ^1.2.0+2
  test: ^1.21.4
#  flutter_easyloading: ^3.0.5
  toggle_switch: ^2.0.1
  pull_to_refresh: ^2.0.0
  fingerprintjs: ^2.0.0
#  rive: ^0.11.4
  open_store: ^0.5.0

#  syncfusion_flutter_pdfviewer: ^20.3.59
  path_provider: ^2.0.11

 # printing: ^5.9.3
  printing: ^5.10.3

#  network_manager: ^0.1.0
  dio_cookie_manager: ^2.0.0
  network_info_plus: ^2.3.0
  flutter_secure_storage: ^6.0.0
  jwt_decoder: ^2.0.1
  get_it: ^7.2.0
  crypto: ^3.0.3
  device_info_plus: ^9.0.3
  card_swiper: ^3.0.1


#  path_provider: ^0.4.1
#  pspdfkit_flutter:
#    git:
#      url: git://github.com/PSPDFKit/pspdfkit-flutter.git
#  latlong2: ^0.8.1

  #flutter_svg: ^1.0.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_places_autocomplete_text_field: ^0.1.3
#  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.3
#  flutter_google_maps_webservices: ^1.1.1
#  flutter_google_places: ^0.3.0
#  google_maps_webservice: ^0.0.20-nullsafety.5
  latlong2: ^0.8.1
  custom_refresh_indicator: ^1.2.1
  geolocator: ^9.0.2
  marquee: ^2.2.3
 # flip_widget: ^0.1.11
#  better_page_turn: ^0.0.6
  flutter_spinkit: ^5.1.0
  image_size_getter: ^2.1.2
#  page_curl: ^0.0.1
#  firebase_auth: ^4.4.2
  expandable: ^5.0.1
  dismissible_page: ^0.7.3
  assorted_layout_widgets: ^9.0.0
  map_launcher: ^2.4.0
  permission_handler: ^11.0.1
  sign_in_with_apple: ^4.3.0
  firebase_core: ^2.25.4
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  pdf_render: ^1.4.0
  scroll_snap_list: ^0.9.1
  animate_icons: ^2.0.0
#  intl: ^0.18.1
  video_player: ^2.7.2
  url_launcher: ^6.1.10
#  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.1.6
  backdrop: ^0.9.1
  google_fonts: ^4.0.4
  qr_code_scanner: ^1.0.1
  uuid: ^3.0.7
  flutter_local_notifications: ^16.3.2
  flutter_card_swiper: ^6.0.0
#  flutter_widget_from_html: ^0.14.11
  flutter_html: ^3.0.0-beta.2
  chewie: ^1.7.4
  page_flip: ^0.2.3
  flutter_widget_from_html: ^0.14.11
  fwfh_webview: ^0.14.8
  flutter_widget_from_html_core: ^0.14.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.9


dependency_overrides:
  intl: ^0.18.0

flutter_icons:
  android: true
  ios: true
#  image_path: "assets/images/appicon@2x.png"
#  remove_alpha_ios: true


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practiceshttps://www.geeksforgeeks.org/union-and-intersection-of-two-sorted-arrays-2/. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg®
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/icons/
    - assets/covers/
    - assets/translations/
   # - assets/PDFtest.pdf
   # - assets/test.mp4
    - assets/images/
    - assets/images/background/Background.png
    - assets/images/map_pins/
    - assets/images/logo/logo.png

   # - assets/translations/
    #- assets/images/pins/

#  fonts:
#    - family: Raleway
#      fonts:
#        - asset: assets/fonts/Raleway-VariableFont_wght.ttf


  # An image asset can refer to one or more resolution-specific "variants", seeq
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages